/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */
var t=function(){return(t=Object.assign||function(t){for(var e,n=1,s=arguments.length;n<s;n++)for(var i in e=arguments[n])Object.prototype.hasOwnProperty.call(e,i)&&(t[i]=e[i]);return t}).apply(this,arguments)},e={"navbar-height":70,"open-class":"open"},n=function(){function t(t){var e=this;void 0===t&&(t={}),this.onWindowResize=function(){return e.changeMenu()},this.element=t.element,this.callbacks=t.callbacks||{},this.settings=this.extendSettings(t.settings||{}),"function"==typeof this.callbacks.onInit&&this.callbacks.onInit(),this.mobileMenu=document.querySelector("[data-menu-breaker-mobile]"),this.openButton=document.querySelector("[data-menu-breaker-open]"),this.closeButton=document.querySelector("[data-menu-breaker-close]"),this.toggleButton=document.querySelector("[data-menu-breaker-toggle]"),this.isOpen=!1,this.changeMenu(),this.menuButton(!0),this.addEventListeners()}return t.prototype.addEventListeners=function(){window.addEventListener("resize",this.onWindowResize)},t.prototype.subLevels=function(){for(var t=0,e=this.element.querySelectorAll(":not(li) > ul > li > ul");t<e.length;t++){var n=e[t],s=n.parentNode.clientWidth,i=n.clientWidth;n.parentNode.offsetLeft+i>window.innerWidth?n.style.marginLeft=-i+s+"px":n.style.marginLeft="0";for(var o=0,l=n.querySelectorAll("li > ul");o<l.length;o++){var c=l[o],r=c.offsetWidth;c.parentNode.parentNode.parentNode.offsetLeft+r+i>window.innerWidth?c.style.marginLeft=-r+"px":c.style.marginLeft=r+"px"}}},t.prototype.open=function(){this.mobileMenu.classList.add(this.settings["open-class"]),this.isOpen=!0,"function"==typeof this.callbacks.onMenuOpen&&this.callbacks.onMenuOpen()},t.prototype.close=function(){this.mobileMenu.classList.remove(this.settings["open-class"]),this.isOpen=!1,"function"==typeof this.callbacks.onMenuClose&&this.callbacks.onMenuClose()},t.prototype.menuButton=function(t){var e=this;t&&(this.openButton&&this.openButton.addEventListener("click",(function(){return e.open()})),this.closeButton&&this.closeButton.addEventListener("click",(function(){return e.close()})),this.toggleButton&&this.toggleButton.addEventListener("click",(function(){e.isOpen?e.close():e.open()}))),this.isOpen&&this.mobileMenu.classList.add(this.settings["open-class"])},t.prototype.desktop=function(){this.mobileMenu.classList.contains(this.settings["open-class"])&&this.mobileMenu.classList.remove(this.settings["open-class"]),this.subLevels()},t.prototype.changeMenu=function(){this.element.offsetHeight>this.settings["navbar-height"]?(this.menuButton(!1),"function"==typeof this.callbacks.isMobile&&this.callbacks.isMobile()):(this.desktop(),"function"==typeof this.callbacks.isDesktop&&this.callbacks.isDesktop())},t.prototype.extendSettings=function(t){var n,s={};for(n in e)s[n]=n in t?t[n]:e[n];return s},t}();window.jQuery&&(window.jQuery.fn.menuBreaker=function(e){return void 0===e&&(e={}),new n(t({element:this},e))});export default n;
//# sourceMappingURL=menu-breaker.esm.js.map
